test_concepts = executable('test_concepts', 'concepts.cpp', dependencies: [zipper_test_dep])
test('concepts', test_concepts)

test_layout_mapping = executable('test_layout_mapping', 'layout_mapping.cpp', dependencies: [zipper_test_dep])
test('layout_mapping', test_layout_mapping)

test_coeffwise_layout_mapping = executable('test_coeffwise_layout_mapping', 'coeffwise_layout_mapping.cpp', dependencies: [zipper_test_dep])
test('coeffwise_layout_mapping', test_coeffwise_layout_mapping)
